# Generated by Django 5.2.8 on 2026-05-07 18:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('timeframe', models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('1h', '1 Hour'), ('1d', '1 Day'), ('1w', '1 Week')], default='1d', max_length=5)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MarketIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_name', models.CharField(default='NEPSE', max_length=50)),
                ('index_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('change', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('percentage_change', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('high', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('low', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_turnover', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_volume', models.BigIntegerField(default=0)),
                ('total_trades', models.IntegerField(default=0)),
                ('advancing', models.IntegerField(default=0)),
                ('declining', models.IntegerField(default=0)),
                ('unchanged', models.IntegerField(default=0)),
                ('is_market_open', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('condition', models.CharField(choices=[('above', 'Price Goes Above'), ('below', 'Price Goes Below')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_triggered', models.BooleanField(default=False)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['symbol']},
        ),
        migrations.RemoveField(
            model_name='stock',
            name='last_traded_price',
        ),
        migrations.AddField(
            model_name='stock',
            name='close_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stock',
            name='company_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stock',
            name='high_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stock',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='low_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stock',
            name='market_cap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='stock',
            name='open_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stock',
            name='point_change',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='previous_close',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stock',
            name='sector',
            field=models.CharField(choices=[('commercial_bank', 'Commercial Bank'), ('development_bank', 'Development Bank'), ('finance', 'Finance'), ('insurance', 'Insurance'), ('hydropower', 'Hydropower'), ('manufacturing', 'Manufacturing'), ('microfinance', 'Microfinance'), ('hotel_tourism', 'Hotel & Tourism'), ('trading', 'Trading'), ('others', 'Others')], default='others', max_length=50),
        ),
        migrations.AddField(
            model_name='stock',
            name='total_listed_shares',
            field=models.BigIntegerField(default=1000000),
        ),
        migrations.AddField(
            model_name='stock',
            name='volume',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='percentage_change',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='candledata',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='stocks.stock'),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='stocks.stock'),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userwatchlist',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlisted_by', to='stocks.stock'),
        ),
        migrations.AddField(
            model_name='userwatchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_watchlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='candledata',
            index=models.Index(fields=['stock', 'timeframe', 'timestamp'], name='stocks_cand_stock_i_3fc364_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candledata',
            unique_together={('stock', 'timestamp', 'timeframe')},
        ),
        migrations.AlterUniqueTogether(
            name='userwatchlist',
            unique_together={('user', 'stock')},
        ),
    ]
