# Generated by Django 5.2.8 on 2026-05-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_trading_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='trading_balance',
            field=models.DecimalField(decimal_places=2, default=500000, help_text='Simulated NPR cash for NEPSE market purchases', max_digits=14),
        ),
    ]
