# Generated by Django 5.2.8 on 2026-03-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='estimated_return_per_year',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='expected_return',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='investment_type',
            field=models.CharField(choices=[('new', 'New Investment'), ('existing', 'Existing Investment')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='investment_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='roi',
            field=models.FloatField(default=0),
        ),
    ]
