# Generated by Django 5.2.8 on 2026-03-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_management', '0002_remove_portfolio_estimated_return_per_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='expected_return',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='investment_type',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='estimated_return_per_year',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='investment_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='roi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
