# Generated by Django 5.2.8 on 2026-05-08 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyusagelog',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
