# Generated by Django 5.2.8 on 2026-01-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('clothing', 'Clothing'), ('emi', 'EMI'), ('misc', 'Miscellaneous'), ('salary', 'Salary'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('saving', 'Saving')], max_length=10),
        ),
    ]
