# Generated by Django 5.2.8 on 2026-05-08 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_forum_system'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='forumpost',
            new_name='community_f_categor_decf12_idx',
            old_name='community_fp_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='forumpost',
            new_name='community_f_like_co_dbc951_idx',
            old_name='community_fp_like_idx',
        ),
        migrations.RenameIndex(
            model_name='forumpost',
            new_name='community_f_created_5dedee_idx',
            old_name='community_fp_date_idx',
        ),
    ]
