# Generated by Django 5.2.8 on 2026-05-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_rename_community_fp_cat_idx_community_f_categor_decf12_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
